#
# This file generated by pbxbuild 
#

include $(GNUSTEP_MAKEFILES)/common.make



APP_NAME=TextEdit

VERSION=264

TextEdit_OBJC_FILES=\
	Controller.m\
	Document.m\
	DocumentController.m\
	DocumentPropertiesPanelController.m\
	DocumentWindowController.m\
	Edit_main.m\
	EncodingManager.m\
	FontNameTransformer.m\
	LinePanelController.m\
	MultiplePageView.m\
	Preferences.m\
	PrintPanelAccessoryController.m\
	ScalingScrollView.m

TextEdit_RESOURCE_FILES=\
	DocumentWindow.nib\
	accessories-text-editor.icns

TextEdit_LOCALIZED_RESOURCE_FILES=\
	DocumentProperties.nib\
	Edit.nib\
	EncodingAccessory.nib\
	InfoPlist.strings\
	LinePanel.strings\
	Localizable.strings\
	Preferences.nib\
	PrintPanelAccessory.nib\
	PrintPanelAccessory.strings\
	SelectEncodingsPanel.nib\
	SelectLinePanel.nib\
	ServicesMenu.strings\
	ZoomValues.strings

TextEdit_LANGUAGES=\
	English



ADDITIONAL_CPPFLAGS += -DGNUSTEP -std=gnu99

include $(GNUSTEP_MAKEFILES)/application.make
